name: Test de connexion Playwright sur Chrome avec envoi par email

on:
  push:
    branches:
      - main
  pull_request:
  # //schedule:
    # - cron: "0 * * * *" # Toutes les heures (UTC)
  schedule:
    - cron: "0 0 1 * *" # Chaque mois, le 1er à minuit UTC



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      # 2️⃣ Installer Node.js
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Installer les dépendances
      - name: Installation des dépendances
        run: npm install

      # 4️⃣ Installer les navigateurs Playwright
      - name: Installation des navigateurs Playwright
        run: npx playwright install --with-deps

      # 5️⃣ Lancer uniquement Login.spec.js sur Chrome avec 2 reporters (html + json)
      - name: Exécution du test Login.spec.js sur Chrome
        run: |
          npx playwright test tests/demo/Login.spec.js --project=chrome --reporter=html,json > results.json

      # 6️⃣ Extraire un résumé des résultats
      - name: Analyse du rapport JSON
        id: summary
        run: |
          passed=$(jq '[.suites[].specs[].tests[].results[] | select(.status=="passed")] | length' results.json)
          failed=$(jq '[.suites[].specs[].tests[].results[] | select(.status=="failed")] | length' results.json)
          echo "passed=$passed" >> $GITHUB_OUTPUT
          echo "failed=$failed" >> $GITHUB_OUTPUT

      # 7️⃣ Sauvegarder le rapport HTML comme artefact
      - name: Sauvegarder le rapport HTML
        uses: actions/upload-artifact@v4
        with:
          name: rapport-playwright
          path: playwright-report/

      # 8️⃣ Envoyer le mail avec résumé en HTML
      - name: Envoi du rapport par email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mail.yahoo.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: >-
            Rapport Playwright Login -
            ${{ job.status == 'success' && '✅ Succès' ||
                job.status == 'failure' && '❌ Échec' ||
                job.status == 'cancelled' && '⚠️ Annulé' ||
                job.status }}
          to: "smailyes05@yahoo.fr"
          from: "smailyes05@yahoo.fr"
          content_type: text/html
          body: |
            <html>
              <body style="font-family: Arial, sans-serif; color:#333;">
                <h2>Rapport du test Playwright : <code>Login.spec.js</code></h2>
                <p>Bonjour,</p>
                <p>Le test a été exécuté. Voici un résumé :</p>
                <table style="border-collapse: collapse; margin: 10px 0;">
                  <tr>
                    <th style="border:1px solid #ccc; padding:8px; background:#f2f2f2;">Statut</th>
                    <th style="border:1px solid #ccc; padding:8px; background:#f2f2f2;">Nombre</th>
                  </tr>
                  <tr>
                    <td style="border:1px solid #ccc; padding:8px;">Réussi</td>
                    <td style="border:1px solid #ccc; padding:8px;">${{ steps.summary.outputs.passed }}</td>
                  </tr>
                  <tr>
                    <td style="border:1px solid #ccc; padding:8px;">Échoué</td>
                    <td style="border:1px solid #ccc; padding:8px;">${{ steps.summary.outputs.failed }}</td>
                  </tr>
                </table>
                <p>Bonne journée,</p>
                <p><strong>L’équipe QA</strong></p>
              </body>
            </html>
