name: Test de connexion Playwright sur Chrome avec envoi par email

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 1 * *" # Chaque mois, le 1er jour à 00:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      # 2️⃣ Node.js
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Dépendances
      - name: Installation des dépendances
        run: npm install

      # 4️⃣ Playwright
      - name: Installation des navigateurs Playwright
        run: npx playwright install --with-deps

      # 5️⃣ Exécution du test Login.spec.js
      - name: Exécution du test Login.spec.js sur Chrome
        run: |
          npx playwright test tests/demo/Login.spec.js --project=chrome --reporter=html,json > results.json

      # 6️⃣ Analyse du rapport JSON
      - name: Analyse du rapport JSON
        id: summary
        run: |
          passed=$(jq '[.suites[].specs[].tests[].results[] | select(.status=="passed")] | length' results.json)
          failed=$(jq '[.suites[].specs[].tests[].results[] | select(.status=="failed")] | length' results.json)
          echo "passed=$passed" >> $GITHUB_OUTPUT
          echo "failed=$failed" >> $GITHUB_OUTPUT

      # 7️⃣ Sauvegarder le rapport HTML comme artefact
      - name: Sauvegarder le rapport HTML
        uses: actions/upload-artifact@v4
        with:
          name: rapport-playwright
          path: playwright-report/

      # 8️⃣ Copier le rapport HTML et mettre à jour latest.html
      - name: Copier rapport HTML et créer latest.html
        run: |
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          TARGET_DIR=docs/reports/run-$TIMESTAMP
          mkdir -p $TARGET_DIR
          cp -r playwright-report/* $TARGET_DIR
          cp $TARGET_DIR/index.html docs/reports/latest.html

      # 9️⃣ Commit et push pour GitHub Pages
      - name: Commit et push rapport HTML
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/reports
          git commit -m "Mise à jour du rapport Playwright"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 🔟 Envoyer le mail avec lien stable vers latest.html
      - name: Envoi du rapport par email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mail.yahoo.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: >-
            Rapport Playwright Login -
            ${{ job.status == 'success' && '✅ Succès' ||
                job.status == 'failure' && '❌ Échec' ||
                job.status == 'cancelled' && '⚠️ Annulé' ||
                job.status }}
          to: "smailyes05@yahoo.fr"
          from: "smailyes05@yahoo.fr"
          content_type: text/html
          body: |
            <html>
              <body style="font-family: Arial, sans-serif; color:#333;">
                <!-- Version texte simple pour clients mail non HTML -->
                <div style="display:none;">
Rapport du test Playwright : Login.spec.js

Réussi: ${{ steps.summary.outputs.passed }}
Échoué: ${{ steps.summary.outputs.failed }}

Vous pouvez consulter le rapport complet ici : https://<TON-UTILISATEUR>.github.io/<NOM-DEPOT>/docs/reports/latest.html

Bonne journée,
L’équipe QA
                </div>

                <!-- Version HTML -->
                <h2>Rapport du test Playwright : Login.spec.js</h2>
                <p>Réussi: ${{ steps.summary.outputs.passed }}</p>
                <p>Échoué: ${{ steps.summary.outputs.failed }}</p>
                <p>Vous pouvez consulter le rapport complet ici : 
                  <a href="https://ilyes35.github.io/Playwright_PageObjectModel/docs/reports/latest.html">Voir le rapport complet</a>
                </p>
                <p>Bonne journée,</p>
                <p><strong>L’équipe QA</strong></p>
              </body>
            </html>
